### ISSUE TITLE
Place single quotes around system ports

### ISSUE THREAD

**Issue by AnweMuc** [funkwerk/compose_format#4]
place single quotes around system ports like '21:21'

docker-compose reference:
Note: When mapping ports in the HOST:CONTAINER format, you may experience erroneous results when using a container port lower than 60, because YAML will parse numbers in the format xx:yy as sexagesimal (base 60). For this reason, we recommend always explicitly specifying your port mappings as strings.

**Comment by lindt** [comment]
should be fixed with #5
